### PR TITLE
Add ability to filter sql statements

### PR DESCRIPTION
**Pull request by schneiderderek**
One of our applications has failing CI build because of `SHOW` queries that are not consistently run. This allows us to manually exclude some queries. I think this is good enough for V1, but down the road we might want to consider allow the client to subscribe/unsubscribe from some filtering rules.

### CODE REVIEW

**Comment by brandonjoyce** [comment]
I agree w/ the default functionality filtering SHOW queries.  Something like this would probably allow the most flexibility:
```
SqlFootprint.start(exclude: [/^SHOW .*$/]) # default functionality
SqlFootprint.start(exclude: []) # don't exclude anything
```
Would that be difficult to add now? (If we like it)

**Comment by schneiderderek** [comment]
@brandonjoyce I like this idea. But, im a little confused. Was this line: 
```ruby
SqlFootprint.start(exclude: [/^SHOW .*$/]) # default functionality
```

a copy/paste mistake?

I like the idea of clients being able to pass in their own exclusion filters, but should we also provide some defaults (maybe even adapter specific)?

**Comment by schneiderderek** [comment]
I reread what you wrote and it makes sense now.

**Comment by schneiderderek** [comment]
@brandonjoyce Can we come back and add this configuration in a later PR?

**Comment by brandonjoyce** [comment]
Sure! LGTM

**Pull request merged**
