### PR TITLE
Support Rails 7

### PR DESCRIPTION
**Pull request by schoetlr**
Updated to be compatible with Rails 7.

I tested with an app that uses Rails 7.

### CODE REVIEW

**Review by brandonjoyce — APPROVED** [review]
LGTM - 👍 HI LUKE!

**Comment by schoetlr** [comment]
Lol.  Hey Brandon!

**Comment by gnarfle** [comment]
OMG HI BRANDON!

**Comment by schoetlr** [comment]
tests pass
Screenshot 2023-11-01 at 3 34 29 PM

**Review by amy-gurski-cmm — APPROVED** [review]
LGTM 🍨

**Pull request merged**
