### PR TITLE
Update ruby versions tested in CI

### PR DESCRIPTION
**Pull request by amygurski**
Remove ruby 2.3 and 2.4 from CI build & add ruby 3.0.

Rails 6 requires ruby >= 2.5. Since sql_footprint >= 3.0.0 only supports rails 6, test in CI accordingly.

Passing PR build with the adjusted ruby versions: https://travis-ci.org/github/covermymeds/sql_footprint/builds/772469224

### CODE REVIEW

**Review by AlexMooney — COMMENTED** [review]
Good call!  If CI passes on Ruby 3.0, could that be added while updating the versions?

**Comment by amygurski** [comment]
Yes, done. Thanks for the suggestion @AlexMooney!

**Review by jrs40492 — APPROVED** [review]
LGTM 🐢

**Comment by AlexMooney** [comment]
I've asked someone at CMM to review this PR.  If they get it done, (looks like CI is not running after all these years) we should follow up with another one to update it to Ruby 2.7-3.2.  🤞

**Comment by amy-gurski-cmm** [comment]
@AlexMooney FWIW CI is still not running, and we haven't gotten anywhere regarding re-enabling it. I don't think this PR achieves anything else so will close. Feel free to open a PR if there are changes you need to use `sql_footprint` in your apps.

**Pull request closed without merging**
